apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-test
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: git@github.com:Bakmurat/ApplicationsUAT.git
    targetRevision: HEAD
    path: nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: nginxtest
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

